version: '3'

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-vol:
    external: true

services:
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    expose:
      - 9100
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - 9090
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana-vol:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - monitoring
